### ISSUE TITLE
(QUESTION) Is there support for this on macOS

### ISSUE THREAD

**Issue by ghost** [rmccrystal/memlib-rs#3]
For example, CSGO on MacOS with M1 Sillicon CPU/GPU/AI

**Comment by rmccrystal** [comment]
Interesting question... Most of the usefulness of the library comes with the abstractions it gives, so as long as you can write a ProcessHandle implementation for MacOS you should be able to use the rest of the features of the library. Note that being on MacOS will make the offsets different from windows versions which would make cheating hard without much MacOS info public, especially being external. Hope this helped!

**Comment by ghost** [comment]
Alright
